version: '3.3'
services:
  db:
    # will build ./docker/db/Dockerfile
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "5432:5432"
  api:
    # will build ./docker/web/Dockerfile
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
     - "3000:3000"