version: '3'
services:
  db:
    # will build ./docker/db/Dockerfile
    build: ./docker/db
    ports:
      - "5432:5432"
  api:
    # will build ./docker/web/Dockerfile
    build: ./docker/api
    ports:
     - "3000:3000"