version: '3.7'
services:

  nginx:
    image: nginx:1.17.9
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - u-online

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c2dproject
    ports:
     - "5432:5432"
    networks:
      - u-online

  api:
    build: .
    restart: on-failure
    command: yarn run start
    tty: true
    networks:
      - u-online
    depends_on: 
      - db   
  
#Docker Networks
networks:
  u-online:
    driver: bridge        
  