version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c2dproject
    ports:
     - "5432:5432"
  api:
    build: .
    depends_on: 
      - db
    restart: on-failure
    ports:
      - "3000:3000"
    command: yarn run start
    tty: true