version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c2dproject
    ports:
     - "5432:5432"
  api:
    build: .
    
    restart: on-failure
    command: yarn run prisma